Librinfo\VarietiesBundle\Entity\Family:
    type: entity
    table: family
    librinfo:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    oneToMany:
        genuses:
            targetEntity: Librinfo\VarietiesBundle\Entity\Genus
            mappedBy: family
            cascade: [ persist ]