# Entity to persist select choices lists
Librinfo\VarietiesBundle\Entity\SelectChoice:
    type: entity
    table: select_choice
    librinfo:
        loggable:     true
    fields:
        label: 
            type:     string
            nullable: false
        value:
            type:     string
            nullable: false
