Librinfo\VarietiesBundle\Entity\Species:
    type: entity
    table: species
    librinfo:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    manyToOne:
        genus:
            targetEntity: Librinfo\VarietiesBundle\Entity\Genus
            inversedBy: specieses
            joinColumn:
                name: genus_id
            cascade: [ persist ]
        plant_category:
            targetEntity: Librinfo\VarietiesBundle\Entity\PlantCategory
            inversedBy: specieses
            joinColumn:
                name: plant_category_id
            cascade: [ persist ]

    oneToMany:
        varieties:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            mappedBy: species
            cascade: [ persist ]