Librinfo\VarietiesBundle\Entity\Species:
    type: entity
    table: species
    librinfo:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true
        code:
            type:     string(15)
        life_cycle:
            type:     string(10)
            nullable: true

    manyToOne:
        genus:
            targetEntity: Librinfo\VarietiesBundle\Entity\Genus
            inversedBy: specieses
            joinColumn:
                name: genus_id
            cascade: [ persist ]
        parent_species:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            inversedBy: subspecieses
            joinColumn:
                name: parent_species_id
            cascade: [ persist ]

    oneToMany:
        varieties:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            mappedBy: species
            cascade: [ persist ]
        subspecieses:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            mappedBy: parent_species
            cascade: [ persist ]