# info: Strain extends SuperVariety (mapped superclass)

Librinfo\VarietiesBundle\Entity\Strain:
    type: entity
    table: strain
    fields:
        # Caractéristiques particulières de la souche
        strain_characteristics:
            type: string(255)
            nullable: true
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: strains
            joinColumn:
                name: variety_id
            cascade: [ persist ]
    oneToMany:
        professional_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional
            mappedBy: strain
            cascade: [ persist , remove]
        amateur_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur
            mappedBy: strain
            cascade: [ persist , remove]
        production_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction
            mappedBy: strain
            cascade: [ persist , remove]
        commercial_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCommercial
            mappedBy: strain
            cascade: [ persist , remove]
        plant_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant
            mappedBy: strain
            cascade: [ persist , remove]
        culture_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCulture
            mappedBy: strain
            cascade: [ persist , remove]
        inner_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner
            mappedBy: strain
            cascade: [ persist , remove]