
Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: professional_descriptions
            joinColumn:
                name: variety_id
            cascade: [ persist ]
            nullable: true
        strain:
            targetEntity: Librinfo\VarietiesBundle\Entity\Strain
            inversedBy: professional_descriptions
            joinColumn:
                name: strain_id
            cascade: [ persist ]
            nullable: true
