
Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: amateur_descriptions
            joinColumn:
                name: variety_id
            cascade: [ persist ]
        strain:
            targetEntity: Librinfo\VarietiesBundle\Entity\Strain
            inversedBy: amateur_descriptions
            joinColumn:
                name: strain_id
            cascade: [ persist ]

