# info: VarietyDescription extends GenericDescription (mapped superclass)

Librinfo\VarietiesBundle\Entity\VarietyDescription:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: fieldset
        type: string
    discriminatorMap:
        variety: VarietyDescription
        professional: VarietyDescriptionProfessional
        amateur: VarietyDescriptionAmateur
        inner: VarietyDescriptionInner
    table: variety_description
