# info: Variety extends SuperVariety (mapped superclass)

Librinfo\VarietiesBundle\Entity\Variety:
    type: entity
    table: variety

    manyToMany:
        plant_categories:
            targetEntity: Librinfo\VarietiesBundle\Entity\PlantCategory
            inversedBy: varieties
            joinTable:
                name: librinfo_varieties_variety_category
    manyToOne:
        species:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            inversedBy: varieties
            joinColumn:
                name: species_id
            cascade: [ persist ]
    oneToMany:
        strains:
            targetEntity: Librinfo\VarietiesBundle\Entity\Strain
            mappedBy: strains
            cascade: [ persist ]