# info: Variety extends SuperVariety (mapped superclass)

Librinfo\VarietiesBundle\Entity\Variety:
    type: entity
    table: variety
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true
        code:
            type:     string(6)
            # TODO: not nullable
            nullable: true
        # cycle végétatif
        life_cycle:
            type:     string(10)
            nullable: true
        # inscrit au catalogue officiel
        official:
            type:     boolean
            nullable: true
        # nom au catalogue officiel
        official_name:
            type:     string(255)
            nullable: true
        # date d'inscription au catalogue officiel
        official_date_in:
            type:     date
            nullable: true
        # date de radiation du catalogue officiel
        official_date_out:
            type:     date
            nullable: true
        # mainteneur au catalogue officiel
        official_maintainer:
            type:     string
            nullable: true
        # taux de germination légal (si inscrit au catalogue officiel) (%)
        legal_germination_rate:
            type:     integer
            nullable: true
        # statut règlementaire
        regulatory_status:
            type:     string(255)
            nullable: true
        # taux de germination AS (%)
        germination_rate:
            type:     integer
            nullable: true
    oneToMany:
        strains:
            targetEntity: Librinfo\VarietiesBundle\Entity\Strain
            mappedBy: variety
            cascade: [ persist ]
        professional_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional
            mappedBy: variety
            cascade: [ persist , remove]
        amateur_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur
            mappedBy: variety
            cascade: [ persist , remove]
        production_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction
            mappedBy: variety
            cascade: [ persist , remove]
        commercial_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCommercial
            mappedBy: variety
            cascade: [ persist , remove]
        plant_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant
            mappedBy: variety
            cascade: [ persist , remove]
        culture_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCulture
            mappedBy: variety
            cascade: [ persist , remove]
        inner_descriptions:
            targetEntity: Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner
            mappedBy: variety
            cascade: [ persist , remove]
    manyToMany:
        plant_categories:
            targetEntity: Librinfo\VarietiesBundle\Entity\PlantCategory
            inversedBy: varieties
            joinTable:
                name: librinfo_varieties_variety_category
    manyToOne:
        species:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            inversedBy: varieties
            joinColumn:
                name: species_id
            cascade: [ persist ]
        