# info: VarietyDescription extends GenericDescription (mapped superclass)

Librinfo\VarietiesBundle\Entity\VarietyDescription:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: fieldset
        type: string
    discriminatorMap:
        variety: VarietyDescription
        professional: VarietyDescriptionProfessional
        amateur: VarietyDescriptionAmateur
        production: VarietyDescriptionProduction
        commercial: VarietyDescriptionCommercial
        plant: VarietyDescriptionPlant
        culture: VarietyDescriptionCulture
        inner: VarietyDescriptionInner
    table: variety_description
    repositoryClass: Librinfo\VarietiesBundle\Entity\Repository\VarietyDescriptionRepository