# info: Variety extends SuperVariety (mapped superclass)

Librinfo\VarietiesBundle\Entity\Variety:
    type: entity
    table: variety

    manyToOne:
        species:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            inversedBy: varieties
            joinColumn:
                name: species_id
            cascade: [ persist ]
    oneToMany:
        strains:
            targetEntity: Librinfo\VarietiesBundle\Entity\Strain
            mappedBy: strains
            cascade: [ persist ]