services:

    librinfo_varieties.admin.family:
        class: Librinfo\VarietiesBundle\Admin\FamilyAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Family, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.family_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls: 
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:CRUD:family_edit.html.twig ] ]

    librinfo_varieties.admin.genus:
        class: Librinfo\VarietiesBundle\Admin\GenusAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls: 
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:CRUD:genus_edit.html.twig ] ]

    librinfo_varieties.admin.genus_embedded:
        class: Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.species:
        class: Librinfo\VarietiesBundle\Admin\SpeciesAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls: 
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:CRUD:species_edit.html.twig ] ]

    librinfo_varieties.admin.species_embedded:
        class: Librinfo\VarietiesBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.variety:
        class: Librinfo\VarietiesBundle\Admin\VarietyAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, LibrinfoVarietiesBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls: 
            - [ setTemplate, [ list, LibrinfoVarietiesBundle:CRUD:list.html.twig ] ] 
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:CRUD:variety_edit.html.twig ] ]
            - [ setTemplate, [ show, LibrinfoVarietiesBundle:CRUD:show.html.twig ] ] 

    librinfo_varieties.admin.plant_category:
        class: Librinfo\VarietiesBundle\Admin\PlantCategoryAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\PlantCategory, LibrinfoBaseEntitiesBundle:TreeableCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.plant_category_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls: 
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:CRUD:plant_category_edit.html.twig ] ]

    librinfo_varieties.admin.variety_description_inner:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_inner_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_professional:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_professional_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
    
    librinfo_varieties.admin.variety_description_amateur:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_amateur_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
              
    librinfo_varieties.admin.variety_description_production:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_production_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
    librinfo_varieties.admin.variety_description_commercial:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionCommercial, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_commercial_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
    librinfo_varieties.admin.variety_description_plant:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_plant_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_culture:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionCulture, LibrinfoCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_culture_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.select_choice:
        class: Librinfo\VarietiesBundle\Admin\SelectChoiceAdminConcrete
        arguments: [~, Librinfo\CoreBundle\Entity\SelectChoice, LibrinfoCoreBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SelectChoice }
