services:

    librinfo_varieties.admin.family:
        class: Librinfo\VarietiesBundle\Admin\FamilyAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Family, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.family_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.genus:
        class: Librinfo\VarietiesBundle\Admin\GenusAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.genus_embedded:
        class: Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.species:
        class: Librinfo\VarietiesBundle\Admin\SpeciesAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.species_embedded:
        class: Librinfo\VarietiesBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.variety:
        class: Librinfo\VarietiesBundle\Admin\VarietyAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo

    librinfo_varieties.admin.strain:
        class: Librinfo\VarietiesBundle\Admin\StrainAdminConcrete
        arguments: [~, Librinfo\VarietiesBundle\Entity\Strain, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.strain_admin.label
              label_translator_strategy: librinfo_core.label.strategy.librinfo
