parameters:
    librinfo:


##########
# FAMILY
##########

        Librinfo\VarietiesBundle\Entity\Family:
            Sonata\AdminBundle\Show\ShowMapper:
                remove: [description, createdAt, updatedAt]
                add:
                    form_group_general:
                        '':
                            latin_name: ~
                            alias: ~
                            description: ~
                            genuses:
                                admin_code: librinfo_varieties.admin.genus
                    form_group_specifics:
                        form_group_misc:
                            createdAt: ~
                            updatedAt: ~
                            createdBy: ~
                            updatedBy: ~
                    _options:
                        tabsOrder: [form_group_general, form_group_genuses, form_group_specifics]

            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                    form_group_genuses:
                        '':
                            genuses:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                    delete: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: false
                                    admin_code: librinfo_varieties.admin.genus_embedded
                    _options:
                        tabsOrder: [form_group_general, form_group_genuses]

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - description
                    _export_format:
                        csv: [name, latinName, alias, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
#            Sonata\AdminBundle\Datagrid\DatagridMapper:
#                add:


##########
# GENUS
##########

        Librinfo\VarietiesBundle\Entity\Genus:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                            family: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - description
                    _export_format:
                        csv: [name, latinName, alias, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~