parameters:
    librinfo:


##########
# FAMILY
##########

        Librinfo\VarietiesBundle\Entity\Family:
            Sonata\AdminBundle\Show\ShowMapper:
                remove: [description, createdAt, updatedAt]
                add:
                    form_group_general:
                        '':
                            latin_name: ~
                            alias: ~
                            description: ~
                            genuses:
                                admin_code: librinfo_varieties.admin.genus
                    form_group_specifics:
                        form_group_misc:
                            createdAt: ~
                            updatedAt: ~
                            createdBy: ~
                            updatedBy: ~
                    _options:
                        tabsOrder: [form_group_general, form_group_genuses, form_group_specifics]

            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                    form_group_genuses:
                        '':
                            genuses:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                    delete: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: false
                                    admin_code: librinfo_varieties.admin.genus_embedded
                    _options:
                        tabsOrder: [form_group_general, form_group_genuses]

            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - description
                    _export_format:
                        csv: [name, latinName, alias, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
#            Sonata\AdminBundle\Datagrid\DatagridMapper:
#                add:


##########
# GENUS
##########

        Librinfo\VarietiesBundle\Entity\Genus:
            Sonata\AdminBundle\Show\ShowMapper:
                remove: [description, createdAt, updatedAt]
                add:
                    form_group_general:
                        '':
                            latin_name: ~
                            alias: ~
                            description: ~
                            specieses:
                                admin_code: librinfo_varieties.admin.species
                    form_group_specifics:
                        form_group_misc:
                            createdAt: ~
                            updatedAt: ~
                            createdBy: ~
                            updatedBy: ~
                    _options:
                        tabsOrder: [form_group_general, form_group_specieses, form_group_specifics]
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                            family: 
                                type: sonata_type_model
                    form_group_specieses:
                        '':
                            specieses:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                    delete: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: false
                                    admin_code: librinfo_varieties.admin.species_embedded
                    _options:
                        tabsOrder: [form_group_general, form_group_specieses]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    family: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - family
                            - description
                    _export_format:
                        csv: [name, latinName, alias, family, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~


#################
# PLANT CATEGORY
#################

        Librinfo\VarietiesBundle\Entity\PlantCategory:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            code:
                                type: text
                            parentNode:
                                type: librinfo_baseentities_treeable
                                class: Librinfo\VarietiesBundle\Entity\PlantCategory
                                required: true
                                label: librinfo.label.parent_category
                                max_node_level: 2
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~


##########
# SPECIES
##########

        Librinfo\VarietiesBundle\Entity\Species:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                            genus:
                                admin_code: librinfo_varieties.admin.genus
                                required: true
                            life_cycle:
                                type: trans
                                catalogue: varieties
                            varieties: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                            genus:
                                type: sonata_type_model
                                _options:
                                    admin_code: librinfo_varieties.admin.genus
                            parent_species:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                                required: false
                                _options:
                                    admin_code: librinfo_varieties.admin.species_embedded
                            life_cycle:
                                type: librinfo_varieties_lifecycle
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - description
                    _export_format:
                        csv: [name, latinName, alias, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~



###############
# SUPER VARIETY
###############

        Librinfo\VarietiesBundle\Entity\Variety:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            latin_name: ~
                            alias: ~
                            species:
                                admin_code: librinfo_varieties.admin.species
                            life_cycle:
                                type: trans
                                catalogue: varieties
                    form_group_technical:
                        '':
                            tkw: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            latin_name:
                                type: text
                                required: false
                            alias:
                                type: text
                                required: false
                            code: ~
                            species:
                                type: sonata_type_model
                                _options:
                                    admin_code: librinfo_varieties.admin.species
                            plant_categories:
                                query_builder: Librinfo\VarietiesBundle\Admin\PlantCategoryAdminConcrete::getAllWithoutRootQB
#                                type: librinfo_baseentities_treeable
#                                class: Librinfo\VarietiesBundle\Entity\PlantCategory
#                                required: false
#                                max_node_level: 3
#                                min_node_level: 2
                            life_cycle:
                                type: librinfo_varieties_lifecycle
                                required: false
                        form_group_offical_catalogue:
                            official: ~
                            official_name: ~
                            official_name: ~
                            official_date_in:
                                type: sonata_type_date_picker
                                required: false
                            official_date_out:
                                type: sonata_type_date_picker
                                required: false
                            official_maintainer: ~
                    form_tab_inner:
                        form_group_inner:
                            _options:
                                description: La liste des champs est encore incomplète...
                    form_tab_professionals:
                        form_group_professionals:
                            professional_descriptions:
                                type: sonata_type_collection
                                by_reference: true
                                required: true
                                btn_add: false
                                label: false
                                type_options:
                                    required: false
                                    delete: false
                                    btn_add: false
                                    label: false
                            _options:
                                description: La liste des champs est encore incomplète...
                    form_tab_amateurs:
                        form_group_amateurs:
                            amateur_descriptions:
                                type: sonata_type_collection
                                by_reference: true
                                required: true
                                btn_add: false
                                label: false
                                type_options:
                                    required: false
                                    delete: false
                                    btn_add: false
                                    label: false
                            _options:
                                description: La liste des champs est encore incomplète...
                    form_group_technical:
                        '':
                            tkw:
                                help: librinfo.help.twk
                            legal_germination_rate:
                                help: librinfo.help.legal_germination_rate
                            germination_rate:
                                help: librinfo.help.germination_rate
                            seed_lifespan:
                                help: librinfo.help.seed_lifespan
                            raise_duration:
                                help: librinfo.help.raise_duration
                            seedhead_yield:
                                help: librinfo.help.seedhead_yield
                            ditance_on_line:
                                help: librinfo.help.ditance_on_line
                            ditance_between_lines:
                                help: librinfo.help.ditance_between_lines
                            plant_density:
                                help: librinfo.help.plant_density
                            area_per_kg:
                                help: librinfo.help.area_per_kg
                            seedheads_per_kg: ~
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_tab_inner
                            - form_tab_professionals
                            - form_tab_amateurs
                            - form_group_technical
                            - form_group_specific
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    speciesName: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - speciesName
                            - description
                    _export_format:
                        csv: [name, latinName, alias, speciesName, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv


##########
# STRAIN
##########

        Librinfo\VarietiesBundle\Entity\Strain:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
            Sonata\AdminBundle\Form\FormMapper:
                add:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    latin_name: ~
                    alias: ~
                    description: ~
                    _options:
                        fieldsOrder:
                            - name
                            - latin_name
                            - alias
                            - description
                    _export_format:
                        csv: [name, latinName, alias, description, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv


#####################
# VARIETY DESCRIPTION
#####################

        Librinfo\VarietiesBundle\Entity\VarietyDescription:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    fieldset: ~
#                    field: ~
#                    value: ~
#                    variety: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            fieldset:
                                type: hidden
                                label_render: false
                            field:
                                type: hidden
                                label_render: false
                            value: ~
#                            variety: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    fieldsdet: ~
#                    field: ~
#                    value: ~
#                    variety: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    fieldset: ~
#                    field: ~
#                    value: ~
#                    variety: ~