services:
#    librinfo_varieties.example:
#        class: Librinfo\VarietiesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    librinfo_varieties.plant_category.listener:
#        class: Librinfo\VarietiesBundle\EventListener\PlantCategoryListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: preFlush }

# SYMFONY CUSTOM FORM TYPES

    librinfo_varieties.form.type.life_cycle:
        class: Librinfo\VarietiesBundle\Form\Type\LifeCycleType
        tags:
            - { name: form.type, alias: librinfo_varieties_lifecycle }