services:
#    librinfo_varieties.example:
#        class: Librinfo\VarietiesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    librinfo_varieties.plant_category.listener:
#        class: Librinfo\VarietiesBundle\EventListener\PlantCategoryListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: preFlush }

# SYMFONY CUSTOM FORM TYPES

    librinfo_varieties.form.type.life_cycle:
        class: Librinfo\VarietiesBundle\Form\Type\LifeCycleType
        tags:
            - { name: form.type, alias: librinfo_varieties_lifecycle }
    librinfo_varieties.form.type.variety_description:
        class: Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionType
        tags:
            - { name: form.type, alias: librinfo_variety_description }
        arguments: [ @doctrine.orm.entity_manager ]
    librinfo_varieties.form.type.variety_description_filter:
        class: Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionFilterType
        tags:
            - { name: form.type, alias: librinfo_variety_description_filter }
        arguments: [ @doctrine.orm.entity_manager ]
    librinfo_varieties.form.type.variety_code:
        class: Librinfo\VarietiesBundle\Form\Type\VarietyCodeType
        tags:
            - { name: form.type, alias: librinfo_varietycode }
# filters
    librinfo_varieties.filter.type.variety_description_filter:
        class: Librinfo\VarietiesBundle\Filter\VarietyDescriptionFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_librinfo_variety_description }

